
CREATE TABLE IF NOT EXISTS app_state (
  id INTEGER PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tv_background (
  id INTEGER PRIMARY KEY,
  mime TEXT NOT NULL,
  data TEXT NOT NULL
);
